version: 0.2

env:
  variables:
    TF_VERSION:               "0.11.7"
    TF_VAR_stage_staging:     "stg"
    TF_VAR_stage_production:  "prd"
    TF_VAR_tfstate_setup_key: "setup.terraform.tfstate"

phases:
  install:
    commands:
      - ./bin/install_build_commands.sh "${TF_VERSION}"

  pre_build:
    commands:
      - . ./bin/export_aws_settings.sh

  build:
    commands:
      - ./bin/create_setup_staging_production.sh

  post_build:
    commands:
      - touch setup.fin
      - echo "terraform completed on `date`"

artifacts:
  files:
    - setup.fin
