version: 0.2

env:
  variables:
    TF_VERSION:                                "0.11.7"
    TF_VAR_stage:                              "dev"
    TF_VAR_tfstate_setup_key:                  "setup.terraform.tfstate"
    TF_VAR_tfstate_service_base_pre_key:       "service.base.pre.dev.terraform.tfstate"
    TF_VAR_tfstate_service_api_key:            "service.api.dev.terraform.tfstate"
    TF_VAR_tfstate_service_base_after_api_key: "service.base.after_api.dev.terraform.tfstate"
    TF_VAR_tfstate_service_web_key:            "service.web.dev.terraform.tfstate"

phases:
  install:
    commands:
      - curl -s -qL -o /usr/bin/jq https://stedolan.github.io/jq/download/linux64/jq
      - chmod +x /usr/bin/jq
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -o terraform.zip
      - sudo mv terraform /bin
      - rm terraform.zip

  pre_build:
    commands:
      # Workaround until TF supports creds via Task Roles when running on ECS or CodeBuild
      # See: https://github.com/hashicorp/terraform/issues/8746
      - export AWS_RAW_CRED=$(curl --silent http://169.254.170.2:80$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI)
      - export AWS_ACCESS_KEY_ID=$(echo $AWS_RAW_CRED | jq -r '.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo $AWS_RAW_CRED | jq -r '.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo $AWS_RAW_CRED | jq -r '.Token')

  build:
    commands:
      # web
      - cd environments/service/web/development/
      - terraform init -backend-config="bucket=${TF_VAR_s3_bucket_terraform_state_id}" -backend-config="key=${TF_VAR_tfstate_service_web_key}"
      - codebuild_name=`terraform output codebuild_destroy_web_name`
      - cd -
      - ./bin/exec_codebuild.sh "$codebuild_name" "$codecommit_web_branch"
      - cd environments/service/web/development/
      - terraform plan -destroy
      - terraform destroy -auto-approve
      - cd -
      - cd environments/service/base/pre/
      - terraform init -backend-config="bucket=${TF_VAR_s3_bucket_terraform_state_id}" -backend-config="key=${TF_VAR_tfstate_service_base_pre_key}"
      - cloudformation_api_stack=`terraform output cloudformation_api_stack`
      - export TF_VAR_apigw_api_id=$(aws cloudformation describe-stack-resource --stack-name "${cloudformation_api_stack}" --logical-resource-id ApiGatewayRestApi | jq -r '.StackResourceDetail.PhysicalResourceId')
      - cd -
      # base
      - cd environments/service/base/after_api
      - terraform init -backend-config="bucket=${TF_VAR_s3_bucket_terraform_state_id}" -backend-config="key=${TF_VAR_tfstate_service_base_after_api_key}"
      - terraform plan -destroy
      - terraform destroy -auto-approve
      - cd -
      # api
      - ./bin/mapping_logs_delete_firehose.sh "$cloudformation_api_stack"
      - cd environments/service/api/development/
      - terraform init -backend-config="bucket=${TF_VAR_s3_bucket_terraform_state_id}" -backend-config="key=${TF_VAR_tfstate_service_api_key}"
      - codebuild_name=`terraform output codebuild_destroy_api_name`
      - cd -
      - ./bin/exec_codebuild.sh "$codebuild_name" "$codecommit_api_branch"
      - cd environments/service/api/development/
      - terraform init -backend-config="bucket=${TF_VAR_s3_bucket_terraform_state_id}" -backend-config="key=${TF_VAR_tfstate_service_api_key}"
      - terraform plan -destroy
      - terraform destroy -auto-approve
      - cd -
      # base
      - cd environments/service/base/pre/
      - terraform init -backend-config="bucket=${TF_VAR_s3_bucket_terraform_state_id}" -backend-config="key=${TF_VAR_tfstate_service_base_pre_key}"
      - terraform plan -destroy
      - terraform destroy -auto-approve
      - cd -

  post_build:
    commands:
      - touch infrastructure_destroy.fin
      - echo "terraform completed on `date`"

artifacts:
  files:
    - infrastructure_destroy.fin
