version: 0.2

env:
  variables:
    TF_VERSION:                                "0.11.7"
    TF_VAR_stage:                              "prd"
    TF_VAR_tfstate_setup_key:                  "setup.terraform.tfstate"
    TF_VAR_tfstate_service_base_pre_key:       "service.base.pre.prd.terraform.tfstate"
    TF_VAR_tfstate_service_api_staging_key:    "service.api.stg.terraform.tfstate"
    TF_VAR_tfstate_service_api_production_key: "service.api.prd.terraform.tfstate"
    TF_VAR_tfstate_service_base_after_api_key: "service.base.after_api.prd.terraform.tfstate"
    TF_VAR_tfstate_service_web_staging_key:    "service.web.stg.terraform.tfstate"
    TF_VAR_tfstate_service_web_production_key: "service.web.prd.terraform.tfstate"
    TF_VAR_tfstate_service_pipeline_key:       "service.pipeline.terraform.tfstate"

phases:
  install:
    commands:
      - ./bin/install_build_commands.sh "${TF_VERSION}"

  pre_build:
    commands:
      - . ./bin/export_aws_settings.sh

  build:
    commands:
      - ./bin/create_production_environment.sh

  post_build:
    commands:
      - touch infrastructure.fin
      - echo "terraform completed on `date`"

artifacts:
  files:
    - infrastructure.fin
