version: 0.2

env:
  variables:
    TF_VERSION:                                "0.11.14"
    TF_VAR_stage:                              "stg"
    TF_VAR_tfstate_setup_key:                  "setup.terraform.tfstate"
    TF_VAR_tfstate_service_base_pre_key:       "service.base.pre.stg.terraform.tfstate"
    TF_VAR_tfstate_service_api_key:            "service.api.stg.terraform.tfstate"
    TF_VAR_tfstate_service_base_after_api_key: "service.base.after_api.stg.terraform.tfstate"
    TF_VAR_tfstate_service_web_key:            "service.web.stg.terraform.tfstate"

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - ./bin/install_build_commands.sh "${TF_VERSION}"

  pre_build:
    commands:
      - . ./bin/export_aws_settings.sh

  build:
    commands:
      - ./bin/create_staging_environment.sh
      - zip -r infrastructure.zip *

  post_build:
    commands:
      - echo "terraform completed on `date`"

artifacts:
  files:
    - infrastructure.zip
